// Component
import Head from "next/head";
import useWindowSize from "../helper/useWindowsSize";

// Function
import { useEffect, useState } from "react";

export default function Home() {
  
  // Stating Management
  const [sidebar, setSidebar] = useState(true);

  // Variable
  const size = useWindowSize();
  const tablet = size.width < 1024 && size.width > 767;

  return (
    <>
      {/* Header */}
      <Head>
        <title>Responsive Design</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Main Content */}
      <main>
        
        {/* Desktop Size */}
        {size.width > 1023 && (

          /* Sidebar */
          <sidebar className={sidebar ? "open-sidebar" : "hidden-sidebar"}>
            <div className="container-fluid border border-dark row">
        
              {/* Text */}
              <p className="text col-10 border mt-3">test</p>

              {/* Icon */}
              <p className="icon col-2 border mt-3 text-center">icon</p>
      
            </div>
          </sidebar>

        )}

        {/* Tablet Size */}
        {tablet && (
          <sidebar className="hidden-sidebar">
              <p className="icon p-3 text-center border mt-3">icon</p>
          </sidebar>
        )}

        {/* Mobile Size */}
        {size.width < 768 && (
          <footbar>
            ayam
          </footbar>
        )}

        {/* Content */}
        <section>
          {size.width >= 1024 && (
            <button
              className="btn btn-primary m-3"
              onClick={() => setSidebar(!sidebar)}
            >
              Click
            </button>
          )}

          ppte
        </section>
      </main>
    </>
  );
}
