// Component
import Head from "next/head";
import useWindowSize from "../helper/useWindowsSize";
import TabletSidebar from "@/components/sidebar/Tablet";
import MobileSidebar from "../components/sidebar/Mobile";

// Function
import { useEffect, useState } from "react";

export default function Home() {

  // Variable
  const size = useWindowSize();
  const desktopSize = size.width >= 1024;
  const tabletSize = size.width <= 1023 && size.width >= 768;
  const mobileSize = size.width <= 767;

  return (
    <>
      {/* Header */}
      <Head>
        <title>Responsive Design</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Main Content */}
      <main>
        
        {/* Desktop Sidebar */}
        {desktopSize && <TabletSidebar />}

        {/* Tablet Sidebar */}
        {tabletSize && <TabletSidebar />}

        {/* Mobile Sidebar */}
        {mobileSize && <MobileSidebar />}

        {/* Content */}
        <section>
        </section>
      </main>
    </>
  );
}
